package com.juanpablo.evermail.exception;

public enum ErrorCode {
    CONFIG_INVALID, LOCAL_TIMEOUT, NETWORK_TIMEOUT, CANCELLED,
    OAUTH_TOKEN_EXPIRED, OAUTH_CONNECTION_FAILED, OAUTH_INVALID_CREDENTIALS,
    OAUTH_TIMEOUT, OAUTH_STATE_MISMATCH, OAUTH_PROVIDER_ERROR, OAUTH_TOKEN_INVALID,
    OAUTH_TOKEN_EXCHANGE_FAILED, OAUTH_REFRESH_FAILED, OAUTH_BROWSER_UNAVAILABLE,
    OAUTH_USERINFO_FAILED, REAUTH_REQUIRED, IMAP_CONNECTION_FAILED, IMAP_FOLDER_NOT_FOUND,
    IMAP_FETCH_FAILED, MAIL_NOT_FOUND, CURSOR_INVALID, SMTP_CONNECTION_FAILED,
    SMTP_SEND_REJECTED, SMTP_REJECTED, DELIVERY_UNKNOWN, LOCAL_SAVE_PENDING,
    DB_CONNECTION_FAILED, DB_QUERY_FAILED, DB_MIGRATION_FAILED,
    CRYPTO_OPERATION_FAILED, KEY_NOT_FOUND, SESSION_UNAVAILABLE,
    IDEMPOTENCY_CONFLICT, INVALID_RECIPIENT, ATTACHMENT_NOT_FOUND, ATTACHMENT_TOO_LARGE
}
